name: React CI Actions
run-name: ${{ github.actor }} is running testing, linting and building 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - name: Starting Checkout v2
        uses: actions/checkout@v2
      - name: Starting Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node modules
        run: npm install
      - name: Build production version
        run: npm run build:prod
      - name: Linting typescript
        run: npm run lint:ts
        if: always()
      - name: Linting styles
        run: npm run lint:scss
        if: always()
      - name: Run unit tests
        run: npm run test:unit
        if: always()
      - name: Build Storybook
        run: npm run storybook:build
        if: always()
      - name: Run screenshot tests
        run: npm run test:ui:ci
        if: always()